import { Testimonial } from "@/types";

export const videoTestimonials: Testimonial[] = [
  {
    id: "bayron",
    name: "Byron",
    quote: "No tuve que operarme",
    videoUrl: "OAm3zlpruY0",
    image: "/images/upload/Byron Herrada Foto.png",
    type: "video",
  },
  {
    id: "xiomara",
    name: "Xiomara",
    quote: "Quería que fuera secreto",
    videoUrl: "K24wjfBe8GE",
    image: "/images/upload/Xiomara Foto.png",
    type: "video",
  },
  {
    id: "hao",
    name: "Hao W.",
    quote: "Mil veces mejor que los normales",
    videoUrl: "FQRNqkHoA6c",
    image: "/images/upload/Hao Foto.png",
    type: "video",
  },
  {
    id: "insta-1",
    name: "Paciente Feliz",
    quote: "Mi proceso con ortodoncia invisible",
    videoUrl: "C8H3V10Rxlm",
    type: "instagram",
  },
  {
    id: "insta-2",
    name: "Testimonio Alineadores",
    quote: "Excelente resultado",
    videoUrl: "DOovYrBEfO3",
    type: "instagram",
  },
  {
    id: "insta-3",
    name: "Paciente Ortodoncia",
    quote: "Una sonrisa nueva",
    videoUrl: "DOJ1q8JkS1h",
    type: "instagram",
  },
  {
    id: "insta-4",
    name: "Paciente Clínica Lingual",
    quote: "Increíbles resultados",
    videoUrl: "DNGaVC9x99-",
    type: "instagram",
  },
  {
    id: "insta-5",
    name: "Cambiando Sonrisas",
    quote: "Tratamiento 100% estético",
    videoUrl: "DMq0H7JMZ6A",
    type: "instagram",
  },
  {
    id: "insta-6",
    name: "Paciente Satisfecho",
    quote: "La mejor atención en Las Condes",
    videoUrl: "DML3q_4RA4n",
    type: "instagram",
  },
  {
    id: "insta-7",
    name: "Ortodoncia Invisible",
    quote: "Cómodo y discreto",
    videoUrl: "DKfoRZ6Rcai",
    type: "instagram",
  },
  {
    id: "insta-8",
    name: "Testimonio Real",
    quote: "Mi experiencia en la clínica",
    videoUrl: "C_3IuZZx1yD",
    type: "instagram",
  },
  {
    id: "insta-9",
    name: "Resultados Alineadores",
    quote: "Sonrisa perfecta en meses",
    videoUrl: "C8r-uvNRlUq",
    type: "instagram",
  },
  {
    id: "insta-10",
    name: "Caso de Éxito",
    quote: "La mejor inversión",
    videoUrl: "C5hFh90rcjQ",
    type: "instagram",
  },
];
